<html>
<head>
    <title>GdprIndexView</title>
</head>
<body>
<h3>Gdpr敏感信息泄露检查</h3>
<ul>
    <li>姓名</li>
    <span>法外张三</span>
    <li>电话</li>
    <span>18888888888</span>
    <li>邮箱</li>
    <span>fawaizhangsan@qq.com</span>
    <li>身份证</li>
    <span>440105199710317492</span>
    <li>地址</li>
    <span>广东省广州市增城区中新镇张三花园小区6栋56号</span>
</ul>
</body>
</html>